image/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path ,include
from . import views

app_name="image"
urlpatterns = [
    path('',views.index,name='imghome'),
    path(r'^delete/(?P<pk>[0-9]+)/$',views.delete,name='imgDelete'),
]

sorab/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index,name="home"),
    path('images/',include('image.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

image/models.py
# from django.db import models
from distutils.command.upload import upload
from email.policy import default
from io import BytesIO
from json import load
from sqlite3 import Timestamp
from django.db import models
from django.forms import IntegerField, JSONField
from django.core.files.base import ContentFile
from keras.models import load_model
import easyocr

from PIL import Image
import math
import cv2 
import numpy as np
import face_recognition
import mediapipe as mp

mp_drawing = mp.solutions.drawing_utils
mp_holistic = mp.solutions.holistic


def gray(img):
    img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    return img

def faceDetection(img):
    faceCascade=cv2.CascadeClassifier(cv2.data.haarcascades+"haarcascade_frontalface_alt.xml")
    imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=faceCascade.detectMultiScale(imgGray,1.1,4)
    res='no face detected'
    if faces == ():
        return None,res
    for (x,y,w,h) in faces:
        res='face detected'
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

    return img,res

def face_extract(img):
    face_cas=cv2.CascadeClassifier(cv2.data.haarcascades+"haarcascade_frontalface_alt.xml")

    face=face_cas.detectMultiScale(img,1.3,5)

    if face == ():
        return None
    arr=[]
    for (x,y,w,h) in face:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face=img[y:y+h,x:x+w]
        arr.append([x,y,w,h])
    return cropped_face,arr



def face_extract_mood(imginp):
    img=imginp
    moods={1:"happy",2:"angry",3:"sad",4:"fear"}
    model=load_model('image/emotionnew.h5') 
    output=""
    face_cas=cv2.CascadeClassifier(cv2.data.haarcascades+"haarcascade_frontalface_alt.xml")

    imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=face_cas.detectMultiScale(imgGray,1.1,4)

    if face == ():
        return imginp,"No Mood Detected"

    for (x,y,w,h) in face:
        # cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face=img[y:y+h,x:x+w]

        faces=cv2.resize(cropped_face,(150,150))
        rgb=cv2.cvtColor(faces,cv2.COLOR_BGR2RGB)

        im=Image.fromarray(rgb,"RGB")
        img_arr=np.array(im)

        img_arr=np.expand_dims(img_arr,axis=0)
        img_arr=np.vstack([img_arr])
        pred=model.predict(img_arr)
        pred=np.argmax(pred)
        prediction=moods[pred+1]
        output+=" "+prediction

        # cv2.putText(imginp, prediction , (x, y+20), cv2.FONT_HERSHEY_PLAIN, 2, (255,255,255), 2)

    return imginp,output

def tedxt_extract(img):
    reader=easyocr.Reader(['en'],gpu=True)
    result=reader.readtext(img)
    arr=[]

    for j in range (len(result)-1):
        top_left=(result[j][0][0])
        bottom_right=(result[j][0][2])

        print(result[j])
        if float(result[j][0][0][0])==int(result[j][0][0][0]):
            # print(str(result[j][1]))
            arr.append(str(result[j][1]))

    return arr

        




# def Gender(imginp):
#     img1=imginp
#     model=load_model("image\gender240.h5")
#     output=""
#     labels=["Female","Male"]

#     img1=cv2.resize(img1,[240,240])
#     img1=np.array([img1])
#     pred=np.argmax(model.predict(img1))
#     output=labels[np.argmax(pred)]

#     return imginp,output
    
    



def face_match(img1,img2):
    image1=img1
    imgTest=img2
    # image1 = face_recognition.load_image_file(img1)
    image1=cv2.cvtColor(image1,cv2.COLOR_BGR2RGB)
    # imgTest=face_recognition.load_image_file(img2)
    imgTest=cv2.cvtColor(imgTest,cv2.COLOR_BGR2RGB)

    faceLoc=face_recognition.face_locations(image1)[0]
    encodeim1=face_recognition.face_encodings(image1)[0]
    # cv2.rectangle(image1,(faceLoc[3],faceLoc[4]),(faceLoc[1]),faceLoc[2],(0,0,255),2)

    faceLoc2=face_recognition.face_locations(imgTest)[0]
    encodeim2=face_recognition.face_encodings(imgTest)[0]
    # cv2.rectangle(imgTest,(faceLoc2[3],faceLoc2[4]),(faceLoc2[1]),faceLoc2[2],(0,0,255),2)

    results=face_recognition.compare_faces([encodeim1],encodeim2)
    resultDis=face_recognition.face_distance([encodeim1],encodeim2)
    return img1,str(results)+" "+str(resultDis)

def posed(image):
    i,mood=face_extract_mood(image)
    mp_pose = mp.solutions.pose
    pose = mp_pose.Pose()
    res='cannot detect pose'
    def calculate_shoulder_angle(landmarks):
        if len(landmarks) >= 13:
            left_shoulder = landmarks[11]
            right_shoulder = landmarks[12]

            # Calculate the angle between the shoulders
            angle_radians = abs(left_shoulder.x - right_shoulder.x) / abs(left_shoulder.y - right_shoulder.y)
            angle_degrees = round(angle_radians * (180.0 / 3.14159265359), 2)
            print(angle_degrees)
            return angle_degrees
        return None
    
    def calculate_angle(vector1, vector2):
        dot_product = sum(x * y for x, y in zip(vector1, vector2))
        magnitude1 = math.sqrt(sum(x ** 2 for x in vector1))
        magnitude2 = math.sqrt(sum(y ** 2 for y in vector2))
        cosine_angle = dot_product / (magnitude1 * magnitude2)
        angle = math.degrees(math.acos(cosine_angle))
        return angle
    
    frame_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = pose.process(frame_rgb)
    if results.pose_landmarks is not None:
        
        landmarks = results.pose_landmarks.landmark
        
        nose_index = 0
        shoulder2_index = 14
        nose = landmarks[nose_index]
        shoulder1 = landmarks[11]
        shoulder2 = landmarks[12]
        
        vector_nose_shoulder1 = [shoulder1.x - nose.x, shoulder1.y - nose.y]
        vector_nose_shoulder2 = [shoulder2.x - nose.x, shoulder2.y - nose.y]
        angle_nose_shoulder1 = calculate_angle(vector_nose_shoulder1, [1, 0])
        angle_nose_shoulder2 = calculate_angle(vector_nose_shoulder2, [1, 0])

        if abs(angle_nose_shoulder1) < 80 and abs(angle_nose_shoulder2 - 60) < 80 and (angle_nose_shoulder1) > 40 and (angle_nose_shoulder2-60) > 40:
            print("Both angles are approximately 60 degrees.")
            res='sitting straight'
        else:
            print("One or both angles are not approximately 60 degrees.")
            res='Sit Straight a bit'
                # print(f"Angle between shoulders: {angle_degrees} degrees")
                
        for landmark in landmarks:
            height, width, _ = image.shape
            cx, cy = int(landmark.x * width), int(landmark.y * height)
            cv2.circle(image, (cx, cy), 5, (0, 255, 0), -1) 
                
        height, width, _ = image.shape
        left_shoulder_x = int(shoulder1.x * width)
        left_shoulder_y = int(shoulder1.y * height)
        right_shoulder_x = int(shoulder2.x * width)
        right_shoulder_y = int(shoulder2.y * height)
        nose_1 = int(nose.x * width)
        nose_2 = int(nose.y * height)

        cv2.circle(image, (left_shoulder_x, left_shoulder_y), 5, (255,0, 0), -1)  # Red dot for left shoulder
        cv2.circle(image, (right_shoulder_x, right_shoulder_y), 5, (255,0, 0), -1)  # Red dot for right shoulder
        cv2.circle(image, (nose_1, nose_2), 5, (0, 0, 255), -1)  # Red dot for right shoulder
    
    j,face=faceDetection(image)
        
    print(mood)
    return image,res,str(mood),str(face)
    # with mp_holistic.Holistic(
    #     min_detection_confidence=0.5,
    #     min_tracking_confidence=0.5) as holistic:

       
    #     image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
        
    #     image.flags.writeable = False
    #     results = holistic.process(image)
    #     if results.pose_landmarks is not None:
    #         landmarks = results.pose_landmarks.landmark
    #         left_shoulder = landmarks[11]
    #         right_shoulder = landmarks[12]

    #         # Calculate the angle between the shoulders
    #         angle_radians = abs(left_shoulder.x - right_shoulder.x) / abs(left_shoulder.y - right_shoulder.y)
    #         angle_degrees = round(angle_radians * (180.0 / 3.14159265359), 2)

    #         print(f"Angle between shoulders: {angle_degrees} degrees")
        
    #     image.flags.writeable = True
    #     image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    #     mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
        
    #     image=cv2.flip(image,1)
    #     return image
    

# Create your models here.
class images(models.Model):
    img_id=models.AutoField(primary_key=True)
    image=models.FileField(upload_to="images/imagedata",default="")
    image2=models.FileField(upload_to="images/imagedata",default="")
    img_name=models.CharField(max_length=50)
    
        
    prediction_face=models.CharField(max_length=50,default="")
    prediction_mood=models.CharField(max_length=50,default="")
    prediction_pose=models.CharField(max_length=50,default="")
    choice=models.IntegerField(default=0)

    def __str__(self):
        return self.img_name
      
    def save(self,*args,**kwargs):
        open_img=Image.open(self.image)

        cv2_img=np.array(open_img)

        predict=""
        img=cv2_img
        # img=gray(cv2_img)
        if self.choice==0:

            img=faceDetection(cv2_img)
        elif self.choice==1:
            open_img2=Image.open(self.image2)
            cv2_img2=np.array(open_img2)
            # img,predict=face_match(open_img,open_img2)
            img,predict=face_match(cv2_img,cv2_img2)

        elif self.choice==2:
            img,predict=face_extract_mood(cv2_img)
        elif self.choice==3:
            predict=tedxt_extract(cv2_img)
        # elif self.choice==4:
        #     img,predict=Mask(cv2_img)
        elif self.choice==5:
            img,pose,mood,face=posed(img)
        elif self.choice==6:
            pass
        

        close_img=Image.fromarray(img)

        buffer=BytesIO()
        close_img.save(buffer,format='png')
        image_png=buffer.getvalue()

        self.prediction_pose=pose
        self.prediction_mood=mood
        self.prediction_face=face

image/views.py
from asyncio.windows_events import NULL
from multiprocessing import Event
from django.shortcuts import get_object_or_404, redirect, render

from image.models import images

def delete(request,pk):
    item=get_object_or_404(images, img_id=pk)
    if request.method=="POST":
        item.delete()
        return redirect("/")
    myitems=images.objects.all()
    return render(request,'image/index.html',{'myitems':myitems})

def index(request):
    function_match={"Face_Detection":0,"Face%":1,"emotion":2,"gender":3,"Mask":4,"Pose":5,"Select":6}
    if request.method=="POST":
        img=request.FILES.get("image","")
        img2=request.FILES.get("image2","")
        img_name=request.POST.get("image_n","")
        choice_func=request.POST.get("Function","")
        choice=function_match[choice_func]
        print(choice)
        if choice==1:
            image=images(image=img,img_name=img_name,image2=img2,choice=choice)
        else:
            image=images(image=img,img_name=img_name,image2="",choice=choice)
        image.save()
        
        myitems=images.objects.all()

        return render(request,'image/index.html',{"myitems":myitems})
    myitems=images.objects.all()
    print(myitems)
    # for i in myitems:
    #     print(i.prediction)

    # dic={}
    # for i in myitems:
    #     dic[i.img_id]=Convert(i.prediction)
        
    #     print(dic[i.img_id])


    return render(request,'image/index.html',{'myitems':myitems})
    # return render(request,'image/index.html',{'myitems':myitems},dic)


def Convert(string):
    li = list(string.split("\n"))
    return li

image/templates/image/index.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Image Predictor</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300&family=Roboto&display=swap" rel="stylesheet">
</head>
<style>
  body {
    font-family: 'Quicksand', sans-serif;
  }

  .row>* {

    display: flex;
    justify-content: space-evenly;
    flex-wrap: wrap;
  }

  img {
    /* box-sizing: border-box; */
    max-height: 500px;
    max-width: 500px;
    border: 2px solid grey;
    box-shadow: 5px 5px 10px grey, 0px 0px 0px black, 0px 0px 0px black;
  }
</style>

<body>

  <div class="container">
    <div class="container-fluid">
      <div class="col-md-10">
        <h1>Posture Pro</h1>
        <h3>ENTER IMAGES TO PERFORM OPERATIONS ON IT</h3>
        <hr>
        <div class="mb-3">
          <form action="/images/" method="post" enctype="multipart/form-data"> {% csrf_token %}
            <label for="formFileSm" class="form-label">Search Image</label>
            <input class="form-control form-control-sm" id="formFileSm" type="file" name="image" required>
            <br>
            <div style="display: none;">
              Operation To be Performed: &nbsp <select name="Function" id="Function" onchange="check()">
                <!-- <option value="Select" selected>Select</option> -->
                <!-- <option value="Face_Detection">Face Detection</option> -->
                <!-- <option value="Face%">Face Match %</option> -->
                <!-- <option value="emotion">Emotion Detection</option> -->
                <!-- <option value="gender">Text Detection</option> -->
                <!-- value was  not changed because then we have to change in model.py-->
                <!-- <option value="Mask">Mask Detection</option> -->
                <option value="Pose">Pose Detection</option>
              </select>
            </div>
            <!-- <div class="" name='Function' style="display: none;" value="Pose">Pose Detection</div> -->
            <br>
            <div class="inp2">


            </div>
            {% comment %} <label for="exampleInputEmail1" class="form-label">Image Name</label> {% endcomment %}
            {% comment %} <input type="text" class="form-control" id="exampleInputEmail1" name="image_n"> {% endcomment %}
            <button class="btn btn-primary my-4" type="submit">Save</button>
          </form>
        </div>
      </div>

    </div>
    <!-- <div class="col-md-6">
      <h1>ENTER IMAGES TO PERFORM OPERATIONS ON IT</h1>
      <div class="mb-3">
        <form action="/images/" method="post" enctype="multipart/form-data"> {% csrf_token %}
          <label for="formFileSm" class="form-label">search image</label>
          <input class="form-control form-control-sm" id="formFileSm" type="file" name="image">
          <br>
          <div>
            Function:<select name="Function" id="Function" onchange="check()">
            <option value="Select"selected >Select</option>
            <option value="Face_Detection">Face Detection</option>
            <option value="Face%">Face Match %</option>
            <option value="emotion">Emotion Detection</option>
            <option value="gender">Gender Detection</option>
            <option value="Mask">Mask Detection</option>
            <option value="Pose">Pose Detection</option>
          </select>
        </div>
          <br>
          <div class="inp2">
            

          </div>
          <label for="exampleInputEmail1" class="form-label">Image Name</label>
          <input type="text" class="form-control" id="exampleInputEmail1" name="image_n">
          <button class="btn btn-primary my-4" type="submit" >Save</button>
        </form>
      </div>
    </div> -->


    <div class="row">
      {% for i in myitems %}
      <div>
        <img src="/media/{{i.image}}" class="rounded float-start" id="img1" alt="" style="height: 400px;">


        {%if i.choice == 1%}
        <img src="/media/{{i.image2}}" class="rounded float-start" id="img2" alt="" style="height: 400px;">
        {%endif%}


      </div>
      <div class="container" style="display: inline; width:20rem; margin-top:30px">
        {%if i.prediction_face == 'face detected'%}
        <div class="alert alert-success d-flex align-items-center" role="alert">
          <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
          </svg>
          {%else%}
          <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            {%endif%}
          <div>
            <p>{{i.prediction_face}}</p>
          </div>
        </div>


        {%if i.prediction_pose == 'sitting straight'%}
        <div class="alert alert-success d-flex align-items-center" role="alert">
          <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
          </svg>
          {%else%}
          <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            {%endif%}
          <div>
            <p>{{i.prediction_pose}}</p>
          </div>
        </div>


        {% if i.prediction_mood == " happy" %}
        <div class="alert alert-success d-flex align-items-center" role="alert">
          <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
          </svg>
          <div>
            <p>{{i.prediction_mood}}</p>
          </div>
        {%elif i.prediction_mood == 'No Mood Detected'%}
          <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <div>
              <p>{{i.prediction_mood}}</p>
            </div>
        {%else%} 
          <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <div>
              <p>Smile A Bit More</p>
            </div>
        {%endif%}
          
        </div>
      </div>
      
      <form action="{% url 'image:imgDelete' i.img_id %}" method="post">{% csrf_token %}

        <button class="btn btn-outline-danger">Delete</button>

      </form>
      <hr>
      {% endfor %}
    </div>
  </div>
  </div>

  <script>
    let val = document.getElementById("Function");
    let img2 = document.querySelector(".inp2");
    img2.style.display = "None";
    function check() {
      d = `Pose Detection`;

      console.log(d)
      if (d == "Face Match %") {
        img2.style.display = "block";
        img2.innerHTML = '<input class="form-control form-control-sm img2" id="formFileSm2" type="file" name="image2">'

      }
      if (d != "Face Match %") {
        img2.style.display = "none";
      }
    }
  </script>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
</body>

</html>